### ISSUE TITLE
admin2: input validation for server props

### ISSUE THREAD

**Issue by qaisjp** [multitheftauto/mtasa-resources#101]
**Describe the bug**
Typing nothing or letters into server props cause a server error.

**To Reproduce**
1. Go to server tab
2. Click on game speed
3. Type `hello` or empty the box
4. Click `set`

**Expected behavior**
`Set` should either be disabled OR input validation is performed and the operation is blocked when you click `Set`.

**Additional context**
Related to #100 so inputting `hello` should not be possible. Only empty inputs need to be checked. Alternatively an empty input can set it to the default.

**Comment by CodyJL** [comment]
There's a setting in the edit box that should allow it to decline everything but numbers.
