### ISSUE TITLE
admin2: overhaul glitches and world properties

### ISSUE THREAD

**Issue by qaisjp** [multitheftauto/mtasa-resources#103]
**Describe the bug**
Since the initial development of `admin2` a number of [world properties](https://wiki.multitheftauto.com/wiki/SetWorldSpecialPropertyEnabled) and [glitches](https://wiki.multitheftauto.com/wiki/SetGlitchEnabled) have been created. These are missing in the interface.

**To do**

1. Evaluate whether we should stick to a list of checkboxes (I think a gridlist of green/red glitches/props would be good, with an on/off column for the colourblind, would be good)
2. Add the extra glitches and props
3. Implement new system if needed
4. Push

**Screenshots**
![image](https://user-images.githubusercontent.com/923242/43047111-91f3a7a4-8dca-11e8-9bbe-dafc09339358.png)
![image](https://user-images.githubusercontent.com/923242/43047114-9c9a37e0-8dca-11e8-86d1-90dedb6337e2.png)
![image](https://user-images.githubusercontent.com/923242/43047117-a3b29b44-8dca-11e8-959d-4db98d8c3197.png)

**Comment by CodyJL** [comment]
I'll make it read the 'World properties' from a table and automatically generate them from there.

**Comment by qaisjp** [comment]
Good idea

**Comment by bsa11b** [comment]
Hey qaisjp , you forget [Quick stand , Fast Sprint] to add in admin panel

And see here : 

https://forum.mtasa.com/topic/115697-some-features-should-be-added-in-admin2/

**Comment by alasmi8** [comment]
https://user-images.githubusercontent.com/923242/43047111-91f3a7a4-8dca-11e8-9bbe-dafc09339358.png

I don’t see quickstand , fastsprint glitch’s in screenshot above 

Please add it
