### ISSUE TITLE
admin2: shutdown reason does not work

### ISSUE THREAD

**Issue by qaisjp** [multitheftauto/mtasa-resources#105]
**Describe the bug**
Shutdown reason does not show a reason to players.

**To Reproduce**
1. Go to Server
2. Click on shutdown
3. Type in a reason
4. Click shutdown
5. See shutdown message

**Expected behavior**
Shutdown reason to show. If feature unavailable in MTA, implement it OR replace with "are you sure" dialog.

**Screenshots (GIF)**
![2018-07-22_16-26-40-min](https://user-images.githubusercontent.com/923242/43047260-6c2f728a-8dcc-11e8-92b0-267b50fff541.gif)

**Comment by MIKI785** [comment]
Is this an issue with admin2? Because it works the way it's supposed to, it passes the reason to the shutdown function. The reason is shown in the server log. It's never shown to the players.

**Comment by qaisjp** [comment]
oh.

I guess we can implement a server quit reason that is shown to clients as
well.

shutdown(log_reason, client_reason)

**Comment by PlatinMTA** [comment]
We could kick all the players with the reason... it should work right
