### ISSUE TITLE
admin2: admin rights button

### ISSUE THREAD

**Issue by qaisjp** [multitheftauto/mtasa-resources#107]
**Is your feature request related to a problem? Please describe.**
admin1 has a "Give admin rights" and "Revoke admin rights" button. Historically this has been kinda buggy.

**Describe the solution you'd like**
Make sure this feature is in admin2, and make sure it is working correctly.

**Describe alternatives you've considered**
Remove this feature from admin2.

**Additional context**
Ported from [Mantis 0005112](https://bugs.mtasa.com/view.php?id=5112)

**Comment by alasmi8** [comment]
Adminright button will exist in admin2 or no ?

**Comment by qaisjp** [comment]
Probably yes

**Comment by qaisjp** [comment]
Thinking about this more, it was probably removed in favour of more flexibility.

Instead of hardcoding the ACL groups to "Admin", it should support adding (or removing) the use to any ACL group.

**Comment by iiN3xT** [comment]
We could add the group as a resource setting then you can edit it

**Comment by qaisjp** [comment]
Well I was thinking it would be an "Add to ACL Group" permission and pop up with a list of groups to add the user to

**Comment by iiN3xT** [comment]
Hmm, I guess we can use this aswell instead of the way I used on last commit

**Comment by rifleh700** [comment]
I think it should be only-admin-panel groups that have permission to 'general.adminpanel'

**Comment by jlillis** [comment]
Resolved via #426
