### ISSUE TITLE
admin2: evaluate use of comboboxes

### ISSUE THREAD

**Issue by qaisjp** [multitheftauto/mtasa-resources#110]
**Describe the bug**
The comboboxes used are actually buttons with some sort of dropdown image. This issue is to track the use of these custom comboboxes.

First task is to see whether we should move to a native combobox or fix the problems with the current system.

Second task would be to move to a new combobox, or fix the issues described below:

**Problems with the current system, and how to reproduce, and what is expected**

You can find a combobox on "Resources tab" -> "View type"

> _What is the problem?_
> You cannot click the button to open the combobox - you must click the dropdown image.
>
> _Why is this bad?_
> Poor UX
>
> _How to reproduce?_
> Click on the button, then click on the dropdown image

> _What is the problem?_
> Clicking the button brings it to the front. If you hold mouse down it will bring it to the front - letting go with mouse outside the button does not send it to the back (if you click the button without moving your mouse then it does send it to the back)
>
> _Why is this bad?_
> It is unexpected behaviour

> _What is the problem?_
> The gridlist is misplaced resulting in weird things being clicked sometimes
>
> _Why is this bad?_
> You would expect more accurate selection
>
> _How to reproduce?_
> "Double click slowly" on the dropdown image. Even though the "map" item is the second item down (for the Resources -> View type combobox) it will select that item.
>
> _What is expected?_
> Maybe make the button disabled, make the gridlist headerless, and push it down a little bit so it is not covering the top?
> Or you can remove the header and make it an empty item that is unselectable?

**Screenshots**
![image](https://user-images.githubusercontent.com/923242/43171955-a4b61b48-8fa4-11e8-983a-4c38fb2d7d05.png)
![image](https://user-images.githubusercontent.com/923242/43171916-691e83a4-8fa4-11e8-94fc-773b70de661b.png)

**Comment by CodyJL** [comment]
I'll be moving these to native combo boxes.

**Comment by qaisjp** [comment]
What I forgot to mention is that the reason this might need evaluating is due to a difference in height (from what I recall, I think these buttons look a bit more shorter than the comboboxes, but I could be wrong).

If you choose to move these to native combo boxes, please can you explain why you've evaluated this is the case? An answer like "it is the same height" or "it requires minimal positioning changes" are valid answers. You don't have to go into detail :)

**Comment by CodyJL** [comment]
Admin panel 1 had an update (after admin panel 2 stopped development) to use the native ones from what I can tell and there's no reason to keep a downgraded system.

**Comment by qaisjp** [comment]
OK. Seems reasonable enough. Go for it 👍
