### ISSUE TITLE
admin2: decide content for "network" tab

### ISSUE THREAD

**Issue by qaisjp** [multitheftauto/mtasa-resources#111]
**Is your feature request related to a problem? Please describe.**
There is a "network" tab and some existing code ([client](https://github.com/multitheftauto/mtasa-resources/blob/master/%5Badmin%5D/admin2/client/main/admin_network.lua), [server](https://github.com/multitheftauto/mtasa-resources/blob/master/%5Badmin%5D/admin2/server/admin_network.lua)). **Let's brainstorm features to put into this tab.**

**Describe the solution you'd like**
This issue does not aim to _implement_ the Network tab. This issue is for us to discuss potential features we can include. A separate issue will be filed by an MTAQA member describing how the "Network" tab will function at a later date.

**What the tab looks like currently**
![image](https://user-images.githubusercontent.com/923242/43176160-7a616ac6-8fba-11e8-9bdd-57d49dda2721.png)

**Comment by MIKI785** [comment]
I suppose it should contain info provided by [getNetworkStats](https://wiki.multitheftauto.com/wiki/GetNetworkStats) and maybe [getPerformanceStats](https://wiki.multitheftauto.com/wiki/GetPerformanceStats) (Packet usage category). And maybe an option to see this info per player.

**Comment by alasmi8** [comment]
@MIKI785

I agree with you

**Comment by jlillis** [comment]
Given the lack of progress here, I'm going to close this for now. The network tab was removed in #178.
