### ISSUE TITLE
admin2: auto focus primary items in tabs

### ISSUE THREAD

**Issue by qaisjp** [multitheftauto/mtasa-resources#112]
**Is your feature request related to a problem? Please describe.**
I find it frustrating having to click onto a search box or input box after changing tab!

**Describe the solution you'd like**
Clicking onto a tab should automatically focus the search box (or for admin chat, the chat input box).

**Additional context**
This is an **enhancement** to be worked on after feature parity is established (or when someone is super duper bored).

**Comment by Dezash** [comment]
But if it is focused onto the search box, pressing the 'p' key would write a letter in the search box rather than closing the panel. That is also frustrating.

**Comment by qaisjp** [comment]
good point. hmm.

**Comment by Dante383** [comment]
We could either move the bind from P to some non-text-applicable key like F6, or add an exit button in the admin panel, but that would be essentially the same as unclicking from the search box and clicking P.

**Comment by jlillis** [comment]
I think this issue is out of scope given the current state of admin2. I'm going to close it for now. Perhaps we can revisit this some other time.
