### ISSUE TITLE
parachute: bumps the required mta version to an higher version than the latest version

### ISSUE THREAD

**Issue by MegaThorx** [multitheftauto/mtasa-resources#117]
**Describe the bug**
The resource parachute bumps the required version higher (1.5.5-9.13176.0) than the latest from the updater (1.5.5-9.12411.0). This confuses and prevent players to join the gameserver.

**To Reproduce**
1. Download the latest mta resources
2. Start the parachute resource

**Expected behavior**
The latest version of mtasa resource should not bump the required mta version higher than the current latest mta version. Maybe create a seperate branch for such changes.

**MTA Client (please complete the following information):**
 - Version 1.5.5-9.12411.0
 - Running in Wine? No

**MTA Server (please complete the following information):**
 - OS: Linux (Docker Debian)
 - Version 1.5.5

**Additional context**
The commit which broke it https://github.com/multitheftauto/mtasa-resources/commit/81e03e1ffd31a128ee925745e64470e653ea271d

Output of the server log
https://i.imgur.com/Ju9P42z.png

**Comment by ccw808** [comment]
As a temp fix, I've reverted the latest zip from https://mirror.mtasa.com/mtasa/resources/

**Comment by qaisjp** [comment]
The commit that causes this has been reverted in 7898b101d54ae4282db13f23057c0451dd76a229.

I apologise for the inconvenience.
