### ISSUE TITLE
Jetpack function causes errors on recent server versions

### ISSUE THREAD

**Issue by ccw808** [multitheftauto/mtasa-resources#118]
**Describe the bug**
Latest resources causes errors such as `attempt to call global 'isPedWearingJetpack' (a nil value)`

**To Reproduce**
1. Open admin panel and give jetpack to player

**Expected behavior**
Player gets jetpack

**MTA Client (please complete the following information):**
 - Version 1.5.5-9.12411
 - Running in Wine? No

**MTA Server (please complete the following information):**
 - OS: Debian
 - Version 1.5.5-9.12250

**Comment by qaisjp** [comment]
I've reverted 81e03e1ffd31a128ee925745e64470e653ea271d in 7898b101d54ae4282db13f23057c0451dd76a229 as a temporary fix for this.

Maybe we should adopt a git-flow workflow for resources (develop, master, hotfix, feature) so we can align resource releases to MTA releases.

Are resources expected to be backwards compatible?

**Comment by ccw808** [comment]
I think the default resources should be compatible with the current minor version i.e. 1.5
