### ISSUE TITLE
Fix spam prevention

### ISSUE THREAD

**Issue by qaisjp** [multitheftauto/mtasa-resources#119]
**Describe the bug**
Spam (chat and command) prevention needs to be done properly. It is too sensitive.

**Expected behavior**
Use a back-off algorithm. DIsable spam prevention for people with certain ACL permissions.

**Comment by qaisjp** [comment]
Your commit does look like it will fix this problem, thank you!

I think chat spam prevention still needs some work, though. I still think using a back-off algorithm is the most effective way (the way it works is something like: the quicker you perform an action, the more aggressive the protection).

**Comment by qaisjp** [comment]
It's fairly common to bind `au 1010` to mouse2 down and `ru 1010` to mouse2 up, so that you can get nitro in cars. When punching other players this can inadvertently trigger spam protection. Perhaps spam protection be moved to its own resource or admin or admin2 instead of in freeroam.

**Comment by ArranTuna** [comment]
The original report has been fixed.
