### ISSUE TITLE
upgrade admin,parachute and freeroam

### ISSUE THREAD

**Issue by hanirouatbi1** [multitheftauto/mtasa-resources#120]
admin : 
WARNING: admin/server/admin_server.lua(Line 1042) [Server] doesPedHaveJetPack is deprecated and may not work in future versions. Please replace with isPedWearingJetpack.
WARNING: admin/client/gui/admin_main.lua(Line 476) [Client] doesPedHaveJetPack is deprecated and may not work in future versions. Please replace with isPedWearingJetpack.

parachute:
WARNING: parachute/skydiving_cl.lua(Line 22) [Client] doesPedHaveJetPack is deprecated and may not work in future versions. Please replace with isPedWearingJetpack.

freeroam:
WARNING: freeroam/fr_client.lua(Line 799) [Client] doesPedHaveJetPack is deprecated and may not work in future versions. Please replace with isPedWearingJetpack.

and fix this error: ERROR: freeroam\fr_client.lua:1016: attempt to index local 'player' (a nill value)

**Comment by qaisjp** [comment]
Fixed in https://github.com/multitheftauto/mtasa-blue/commit/ba425866f98dd86a33a3983c4b381972f12a2762

**Comment by lamjed001** [comment]
@qaisjp ok please fix ERROR: freeroam\fr_client.lua:1016: attempt to index local 'player' (a nill value)
