### ISSUE TITLE
Web Resource doesnt work due jQuery

### ISSUE THREAD

**Issue by ghost** [multitheftauto/mtasa-resources#130]
**Which resource(s) have this problem?**
(Please do not include the resource in the title as we will assign a label)
webmap

**Describe the bug**
Whenever you open your webbrowser and access the resource / html file, you're getting the following error: 

> script.js:17 Uncaught ReferenceError: $ is not defined
>     at init (script.js:17)
>     at onload (map.htm:14)

**To Reproduce**
1. start the resource
2. load the http page (http://localhost:22005/webmap/map.htm on localhost)

**Additional context**
Maybe we should remove ajax resource and make use of jquery - we're not living in the past...

- Luxy.c

**Comment by qaisjp** [comment]
This issue doesn't make any sense other than "remove Ajax use jQuery"

What is this issue actually about?

**Comment by xLuxy** [comment]
It does make sense. I also said "MAYBE" - not that we should.

Back to the issue exactly
script.js file basically uses jQuery syntax aka this line:
`	map = new OpenLayers.Map( $('map'), {'maxResolution': 360/512, 'maxExtent':new OpenLayers.Bounds(-90.0,-90.0,90.0,90.0),
	'numZoomLevels':6,
	});`

will fix it and commit a change on that later on.

- Luxy.c

**Comment by qaisjp** [comment]
`document.querySelector` / `document.querySelectorAll` can be used instead of `$('map')`

**Comment by xLuxy** [comment]
Also OpenLayers should be removed or jQuery should be added because it uses jQuery internally. After resolving the above issue, theres another error (from OpenLayers.js):

![error](https://i.gyazo.com/94e1af2c7e4d547832eecae3b927fd77.png)

- Luxy.c

**Comment by qaisjp** [comment]
I get a different error after fixing the `$()` usage:

![image](https://user-images.githubusercontent.com/923242/46250933-c7dd0500-c43d-11e8-83eb-46f385408fec.png)

Are you sure OpenLayers.js uses jQuery? I can't find anything about this online

**Comment by xLuxy** [comment]
Thats what i'm also getting - working on it atm.

- Luxy.c

**Comment by eAi** [comment]
I wrote this resource initially, many years ago. I wasn't aware it has a dependency on opencoding.net (which I still own, but has changed significantly since then).

If there are particular files that are missing let me know - happy to re-host them at code.opencoding.net, if we can't work out what they are and find them. I have most of that stuff backed up, but I can't see immediately what files are missing.

**Comment by jlillis** [comment]
@eAi A [quick search](https://github.com/multitheftauto/mtasa-resources/search?q=opencoding.net) of the code shows that webmap and element browser are looking for the following assets from code.opencoding.net:
- mta/updatesite
- tilecache/tilecache.cgi

One thing to consider, especially if the above assets cannot be recovered from backup: do we want to continue maintaining these web-based interfaces? My experience has been that they are not commonly used anymore and are ready for retirement.

**Comment by patrikjuvonen** [comment]
This is fixed in https://github.com/multitheftauto/mtasa-resources/pull/281

**Comment by jlillis** [comment]
Fixed in #281
