### ISSUE TITLE
Allow us to copy mod details in admin panel to acpanel or clipboard ctrl + c

### ISSUE THREAD

**Issue by bsa11b** [multitheftauto/mtasa-resources#146]
![image](https://user-images.githubusercontent.com/923242/56472336-0deacc00-6455-11e9-93d2-8707ec602d46.png)

i want to select all mod files and copy it to acpanel resource or clipboard ctrl + c

it is hard to find mod files and write it in acpanel manually

**Comment by qaisjp** [comment]
Seems reasonable

**Comment by bsa11b** [comment]
Then , Do it !

**Comment by qaisjp** [comment]
All in good time - we are all doing a lot of work (alongside our own lives!)

Please be a little patient!

**Comment by bsa11b** [comment]
Ok ، I appreciate your efforts

MTA need more developers to do all features, bugs request.

**Comment by CAgent47** [comment]
You can use a simple bash script to find all `.lua` or resource files and copy them to a target directory.

Example (Linux):

```bash
find /path/to/mta/server/mods/deathmatch/resources -type f \( -name "*.lua" -o -name "*.xml" \) -exec cp {} /path/to/acpanel/resources/ \;
```

For Windows, you can use PowerShell:

```powershell
Get-ChildItem -Path "C:\path\to\mta\server\mods\deathmatch\resources" -Recurse -Include *.lua, *.xml | Copy-Item -Destination "C:\path\to\acpanel\resources" -Force
```

If you just need a list of files (to paste manually), run:

```bash
find /path/to/resources -type f \( -name "*.lua" -o -name "*.xml" \) > file_list.txt
```

Then open `file_list.txt` and copy its content.

No need to do it manually.
