### ISSUE TITLE
Request : Automatically resource refresh in admin panel

### ISSUE THREAD

**Issue by bsa11b** [multitheftauto/mtasa-resources#147]
Hi ,

In admin panel , i restart the admin resource whenever i upload new resource because i can’t find it unless restart admin panel !

Please make automatically resource refresh in admin panel

**Comment by qaisjp** [comment]
Seems reasonable but I'm surprised there's not a `refresh list` button in the admin panel?

**Comment by bsa11b** [comment]
If it automatically without refresh list button will better.

**Comment by qaisjp** [comment]
automatically will not be possible

**Comment by WADmitry** [comment]
There is "Refresh List" button.

**Comment by WADmitry** [comment]
![refresh](https://user-images.githubusercontent.com/48402140/56867188-b5936b80-6a0c-11e9-97ae-892d503743f9.png)

**Comment by bsa11b** [comment]
https://github.com/multitheftauto/mtasa-resources/issues/147#issuecomment-487390155

Qaisjp surprise

**Comment by qaisjp** [comment]
Surprised because I thought there was one 😉 

Clearly there is one: https://github.com/multitheftauto/mtasa-resources/blob/master/%5Badmin%5D/admin/client/gui/admin_main.lua#L157

Just click that button @bsa11b and your new resource should appear

**Comment by bsa11b** [comment]
Okay , close this issue.
