### ISSUE TITLE
Screenshots cannot be viewed after creating them

### ISSUE THREAD

**Issue by xerox8521** [multitheftauto/mtasa-resources#156]
**Which resource(s) have this problem?**
admin

**Describe the bug**
When creating a screenshot via the admin panel you can not view it again.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open Admin Panel
2. Select any player
3. Click screenshots
4. Take a new screenshot
5. Select the screenshots from the menu
6. Click on View
7. Observe that if you try to view it again you won't be able to access it

**Expected behavior**
Selected screenshot to be shown

**Version**
Server v1.5.6-release-18427
Client v1.5.6-release-18427.3
Windows 10 - 64 Bit

**Additional context**
Server Error Messages:
```WARNING: admin\server\admin_screenshot.lua:54: Bad usage @ 'fileOpen' [unable to load file 'screenshots/1.jpg']
WARNING: admin\server\admin_screenshot.lua:55: Bad argument @ 'fileGetSize' [Expected scriptfile at argument 1, got boolean]
WARNING: admin\server\admin_screenshot.lua:55: Bad argument @ 'fileRead' [Expected scriptfile at argument 1, got boolean]
WARNING: admin\server\admin_screenshot.lua:56: Bad argument @ 'fileClose' [Expected scriptfile at argument 1, got boolean]
WARNING: admin\server\admin_screenshot.lua:54: Bad usage @ 'fileOpen' [unable to load file 'screenshots/1.jpg']
WARNING: admin\server\admin_screenshot.lua:55: Bad argument @ 'fileGetSize' [Expected scriptfile at argument 1, got boolean]
WARNING: admin\server\admin_screenshot.lua:55: Bad argument @ 'fileRead' [Expected scriptfile at argument 1, got boolean]
WARNING: admin\server\admin_screenshot.lua:56: Bad argument @ 'fileClose' [Expected scriptfile at argument 1, got boolean]
```
Client Error Messages:
```
WARNING: admin\client\gui\admin_screenshot.lua:133: Bad argument @ 'fileWrite' [Expected string at argument 2, got nil]
WARNING: admin\client\gui\admin_screenshot.lua:136: Bad argument @ 'addEventHandler' [Expected element at argument 2, got nil]
```
Not sure if this is also relevant:

CEGUI Error Message:
```
(Error)	Exception: Failed to create Texture object from file 'C:\Program Files (x86)\MTA San Andreas 1.5\mods\deathmatch\resources\admin\screenshots\1560438598.jpg
```

**Comment by FileEX** [comment]
Are you sure that talk about ``admin2``? Because admin2 resource haven't options to take screenshots

**Comment by xerox8521** [comment]
Sorry fixed it!

**Comment by FileEX** [comment]
I can't reproduce this. For me this works correctly. Maybe you use some old version of resources?

**Comment by xerox8521** [comment]
Using 1.5.5 which comes with the mta sa installation.

**Comment by FileEX** [comment]
Please get admin resource from https://github.com/multitheftauto/mtasa-resources/tree/master/%5Badmin%5D and test

**Comment by qaisjp** [comment]
(or https://mirror.mtasa.com/mtasa/resources/mtasa-resources-latest.zip)

**Comment by xerox8521** [comment]
used the link qaisjp posted and it works fine now.

**Comment by CarlRayanitch** [comment]
good idea, or what if the screen flashes when a screenshot is taken
