### ISSUE TITLE
freecam:setPlayerFreecamOption not work

### ISSUE THREAD

**Issue by MrPoper** [multitheftauto/mtasa-resources#165]
**Which resource(s) have this problem?**

freecam
**Describe the bug**

ERROR:server trigged clientside doSetfreecamOption,butevent is not marked as remotely triggerable. 
function not work but thee trigger event not remotely as true
**To Reproduce**

**Expected behavior**

addEvent("doSetFreecamOption",true)
**Screenshots**

ERROR:server trigged clientside doSetfreecamOption,butevent is not marked as remotely triggerable. 

**Version**
 he doesn't need it because he's just a simple bug

**Additional context**

 he doesn't need it because he's just a simple bug

**Comment by Lpsd** [comment]
Thanks for the issue!

I have created a pull request with the relevant change.
