### ISSUE TITLE
admin2: clearchat command

### ISSUE THREAD

**Issue by qaisjp** [multitheftauto/mtasa-resources#168]
**Describe the solution you'd like**

the `/clearchat` command should clear the chat.

**Additional context**

1. It should be its own entry in acl.xml
2. The defaults should match setPlayerMuted imo
3. Please also backport to regular admin resource

**Comment by AfuSensi** [comment]
What do you mean by ```The defaults should match setPlayerMuted imo``` ?
As i understand, /clearchat would clear all messages from the chatbox, is this correct?

**Comment by qaisjp** [comment]
`/clearchat` will call `clearChatBox`

I'm not sure if it should use `hasObjectPermissionTo(player, "function.clearChatBox", false)` or `hasObjectPermissionTo(player, "command.clearchat.", false)`

The `false` there means by default they DON'T have permission.

The `Admin`, `SuperModerator`, `Moderator` groups need to have permission by default, so it needs to be added to [acl.xml](https://github.com/multitheftauto/mtasa-blue/blob/ded201f615e46c30f8402937df5dcb956e1c0a77/Server/mods/deathmatch/acl.xml) and I think someplace else.

**Comment by qaisjp** [comment]
Done in #169
