### ISSUE TITLE
EDF Can't open properties window for object element 

### ISSUE THREAD

**Issue by xLivex** [multitheftauto/mtasa-resources#175]
**Which resource(s) have this problem?**
editor

**Describe the bug**
 Well you can't open the properties window by double click or other way

**To Reproduce**
just create s simple edf file like this
```xml
<def name="test">
    <element name="custom_object" friendlyname="Custom Object" icon="edf/object.png">
        <data name="model" type="objectID" default="1271" />
        <data name="position" type="coord3d" default="0,0,0" />
        <data name="rotation" type="coord3d" default="0,0,0" />
        <object model="!model!" position="!position!" rotation="!rotation!" />
    </element>
</def>
```
then spawn custom_object and try to double click nothing happens only with object

**Comment by arfni** [comment]
The objects collisions get disabled when selecting it which results in processLineOfSight not picking it up anymore.

https://github.com/multitheftauto/mtasa-resources/blob/e39ac5638524189a72ae5bd0e58666dd4bb49fde/%5Beditor%5D/editor_main/client/main.lua#L760-L761


Even if you can still open the properties by pressing F3, this is pretty annoying.
