### ISSUE TITLE
runcode resource should log executed lua strings

### ISSUE THREAD

**Issue by xLuxy** [multitheftauto/mtasa-resources#180]
**Is your feature request related to a problem? Please describe.**

Currently, the runcode resource is not logging anything when someone runs a lua string which could potentially lead to abusive behaviours.

**Describe the solution you'd like**

Write executed string & info about that user to a log file (or `outputDebugString` ?)

What do you guys think about it ?

**Comment by qaisjp** [comment]
Logging is a good idea. I think in some scenarios it does `outputServerLog`: https://github.com/multitheftauto/mtasa-resources/blob/ebc29fd1b0c9567172bfb526cbfee6b88ef36efa/%5Badmin%5D/runcode/server_util.lua#L15-L25 but something should be output to the server log in all scenarios.
