### ISSUE TITLE
(Race Gamemode) End map when only spectators are left

### ISSUE THREAD

**Issue by Joshimuz** [multitheftauto/mtasa-resources#191]
**Is your feature request related to a problem? Please describe.**
The race state is normally set to "EveryoneFinished" whenever... well everyone finishes a race. This skips the "timeafterfirstfinish" waiting time and starts a vote for the next map. However this race state is never set when there are spectators still left watching the race after all non-spectating players have finished. This makes it quite frustrating to have any spectators.

**Describe the solution you'd like**
Set the race state to "EveryoneFinished" when all non-spectating players have finished, as opposed to every single player currently on the server. Perhaps making a new setting to configure whether you'd like to skip waiting for spectators or not.

**Describe alternatives you've considered**
It is possible to just lower the "timeafterfirstfinish" amount to lower the wait, however then you have issues with people who are trying to race not finishing in time. For longer races you want a higher "timeafterfirstfinish" but for shorter ones waiting for say a minute after a 20 second race for some spectators slows things down a lot.

**Additional context**
I was planning on adding an afk script to a race server whereby afk players are forced into spectator mode as opposed to just kicking them from the server (say for instance they crashed out early and don't want to continue, or don't like the map and would like to just watch) however with spectators holding the races up it's not worth doing.

**Comment by Joshimuz** [comment]
Looking into this it seems that the key to implementing this relies around "getActivePlayerCount" and the "activePlayerList".
Somehow remove spectating players from it and re-add un-spectating players to it.

**Comment by Joshimuz** [comment]
OK I've got this working, but not in a way I'm comfortable with pull requesting.
Basically in "onClientReuqestSpecate" I've added a "removeActivePlayer(player)" when enabled and the opposite in the disabled.
Then also in the enabled section I have active player count check and if it's under 1 I set state to EveryoneFinished and end the map.
It has a lot of issues though, if you then un-spectate you can drive around when the map should've ended (but even if you finish it doesn't seem to break anything) and who knows what else.

**Comment by xLuxy** [comment]
Doesnt `onPlayerFinish` event fit your needs ?
