### ISSUE TITLE
admin2: Admins nickname is not displayed in certain messages

### ISSUE THREAD

**Issue by xLuxy** [multitheftauto/mtasa-resources#199]
**Which resource(s) have this problem?**
admin2

**Describe the bug**
Some actions do not display the proper admin name (for example giving a vehicle). Dunno if that's related to not being logged in but it seems wrong.

**To Reproduce**
Add `user.*` in Admin ACL and then give yourself a vehicle while not being logged in.

**Expected behavior**
Show player's nickname rather than just `Admin`

**Screenshots**
![image](https://user-images.githubusercontent.com/8040605/82577674-99b8b580-9b8b-11ea-98cd-19f5cc9633e7.png)
![image](https://user-images.githubusercontent.com/8040605/82577045-b7394f80-9b8a-11ea-898e-efc8570dc809.png)

**Additional context**
Going to fix that one - just opened an issue to keep track of that.

**Comment by qaisjp** [comment]
I think this is fine. Maybe you could make this a resource setting? `local isAnonymous = get("admin2.anonymousActions") != "false"`

**Comment by xLuxy** [comment]
Or we simply add "Anonymous Admin" functionality back - like admin1 has?

**Comment by qaisjp** [comment]
Actually, yes, the original anonymous admin checkbox from admin1 is perfectly fine.

**Comment by qaisjp** [comment]
Fixed in 1b99a05b948abd74df5cea97b7f5b71ed0b22be9
