### ISSUE TITLE
Duplicated options

### ISSUE THREAD

**Issue by FileEX** [multitheftauto/mtasa-resources#209]
**Which resource(s) have this problem?**
admin2

**Describe the bug**
Admin chat settings is duplicated in "Admin Chat" and "Options" tabs.

**To Reproduce**

**Expected behavior**
Remove option from admin chat or options tab

**Screenshots**
![image](https://user-images.githubusercontent.com/26044224/83413441-1feeba80-a41c-11ea-8005-0da0b927a341.png)
![image](https://user-images.githubusercontent.com/26044224/83413471-2aa94f80-a41c-11ea-92ca-9207ce273f57.png)

**Version**
1.5.7

**Additional context**

**Comment by galeapatrik** [comment]
It’s actually useful to be in two places, but unnecessary.

**Comment by galeapatrik** [comment]
But here is the PR #210 if needed.

**Comment by jlillis** [comment]
I did this intentionally for user convenience.
