### ISSUE TITLE
race: missing countdown images

### ISSUE THREAD

**Issue by jlillis** [multitheftauto/mtasa-resources#214]
**Which resource(s) have this problem?**
race

**Describe the bug**
The race resource is missing countdown images 6.png, 5.png, and 4.png, resulting in errors.

**To Reproduce**
1. Start a race
2. Watch debugscript

**Log entries**
`WARNING: race\countdown_client.lua:60: File not found @ 'guiCreateStaticImage' [img/countdown_6.png]

WARNING: race\countdown_client.lua:60: File not found @ 'guiCreateStaticImage' [img/countdown_5.png]

WARNING: race\countdown_client.lua:60: File not found @ 'guiCreateStaticImage' [img/countdown_4.png]`

**Version:**
- server/client 1.5.7 stale
- mtasa-resources master (as of writing)

**Additional context**
To fix this, we could either a: find (or make) the missing images and add them or b: shorten the countdown to just 3 seconds.

**Comment by xLivex** [comment]
I prefer option b
why the countdown starts from 6 anyway?
it should be 5 or 3
