### ISSUE TITLE
setPedArmor client-side does not work on localPlayer

### ISSUE THREAD

**Issue by bum8hj** [multitheftauto/mtasa-resources#235]
**Describe the bug**
- setPedArmor does not work client-side and always outputs false **when used on localPlayer**.

**To Reproduce**
```lua
addCommandHandler("givearmor", function()
    setPedArmor(localPlayer, 100)
    print(setPedArmor(localPlayer, 100))
end)
```

**Expected behavior**
- The localPlayer should get 100 armor.

**Version**
- Multi Theft Auto v1.5.7-release-20632
- MTA:SA Server v1.5.7-release-20632

**Additional context**
- Even with `<min_mta_version server="1.5.7"/>` in the meta, it didn't work.

**Comment by xLive** [comment]
The function only works with client-side peds

Also this repository for MTA Resources only

**Comment by bum8hj** [comment]
Can it work for the localPlayer in the future? Just like setElementHealth.

Edit: oh sorry, didn't notice I posted it in the wrong rep

**Comment by Pirulax** [comment]
Yeah, I probably know the cause of this, its my commit, please move this to `mtasa-blue`
Edit: It only works on client-side only entities (and localplayer isn't a local-only).
Source code: 
```cpp
if (!ped->IsLocalEntity())
    return false;
```

**Comment by bum8hj** [comment]
Gonna assume that I have to close this in order to "move it" to `mtasa-blue`

**Comment by xLive** [comment]
They can move it 
just wait if you want to

**Comment by bum8hj** [comment]
Oops, I already opened the issue there 😅
