### ISSUE TITLE
Implement additional rotation attributes in race spawnpoints

### ISSUE THREAD

**Issue by ArranTuna** [multitheftauto/mtasa-resources#236]
**Is your feature request related to a problem? Please describe.**
The race script currently only supports the 'rotation' attribute in spawnpoints, which maps to the rotZ parameter of createVehicle.

**Describe the solution you'd like**
Since the map editor already allows you to set the spawnpoint rotation in all 3 axis, I think this should be fairly easy to implement in race as well.

A sample implementation:

[racemap.lua]
g_MapObjAttrs = {
spawnpoint = { 'position', 'rotation', 'vehicle', 'paintjob', 'upgrades', 'rotX', 'rotY', 'rotZ' },

[race_server.lua]
local x, y, z = unpack(spawnpoint.position)
...
vehicle = createVehicle(spawnpoint.vehicle, x, y, z, spawnpoint.rotX or 0, spawnpoint.rotY or 0, spawnpoint.rotation, plate:sub(1, 8))

**Additional context**
https://bugs.mtasa.com/view.php?id=5992

**Comment by patrikjuvonen** [comment]
> I have fixed this. But i dont know how to open a pull request. Here are the fixed files that add rotation support to RACE + they fix deprecated functions:
> 
> https://www.dropbox.com/s/6csip5rj198iua2/Race_res.zip?dl=0

@Einheit-101 Hey, are you able to create a pull request for this issue?

**Comment by ArranTuna** [comment]
Click "Pull requests" tab then "new pull request".

**Comment by Einheit-101** [comment]
I guess my race resource that i attached is very old, maybe i look into this again

**Comment by AlexTMjugador** [comment]
> I guess my race resource that i attached is very old, maybe i look into this again
@Einheit-101 A PR is just a way to request the maintainers of a repository to merge commits that were done on top of a common commit in another repository. I'd recommend you to make a fork of this repository (or update it, if you have your own personal fork already), and then apply your changes on top of that. You may find [this random online tutorial](https://yangsu.github.io/pull-request-tutorial/) useful.

**Comment by qaisjp** [comment]
Instead of faffing about with the command line (assuming you're a Git newbie), I'd recommend getting GitHub Desktop, forking, and then making a PR from there.

- Get GitHub Desktop: https://desktop.github.com
- Fork and clone: https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/cloning-and-forking-repositories-from-github-desktop
- Create a pull request: https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/creating-an-issue-or-pull-request
