### ISSUE TITLE
Map settings aren't being saved

### ISSUE THREAD

**Issue by sh4z4n** [multitheftauto/mtasa-resources#237]
**Which resource(s) have this problem?**
editor_main.

**Describe the bug**
Basically everytime the map is reopened or you stop testing it the settings reset.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open a map.
2. Click on map settings, change ghostemode to true (just an example).
3. Save the map.
4. Restart editor_main.

**Expected behavior**
Save the settings.

**Addtional context**
For what I've seen it only saves the environment settings.

**Comment by ArranTuna** [comment]
After trying to reproduce the bug I concluded that no change is necessary because you shouldn't be restarting editor_main on it's own and if you actually load the map again the settings do load correctly, your steps don't mention you reloading the map.
