### ISSUE TITLE
Add ability to lock objects in Map Editor

### ISSUE THREAD

**Issue by turret001** [multitheftauto/mtasa-resources#238]
**Is your feature request related to a problem? Please describe.**
When I have a large ground object placed, I sometimes accidentally click on it and move it.

**Describe the solution you'd like**
It would be really nice to have an option to 'lock' objects, making them unclickable. This could be very useful for interior mappers.

**Comment by xLuxy** [comment]
How would you be able to `unlock` them if you cannot select them? Using element browser might not be a good idea imo.

**Comment by turret001** [comment]
Element browser would not be a good idea at its current state, however; adding filters to it like
[ ] Locked
[ ] Collisionless 
[ ] Nighttime Objects
would make it more feature-rich. 

...so, you would check the Locked box to see locked objects and select them

**Comment by xLive** [comment]
How about using the 'L' key to lock/unlock?

**Comment by turret001** [comment]
> How about using the 'L' key to lock/unlock?

Good idea! but I would like to be able to select objects using element browser as well
