### ISSUE TITLE
Webmap Shows Blank

### ISSUE THREAD

**Issue by turret001** [multitheftauto/mtasa-resources#241]
**Which resource(s) have this problem?**
Webmap (maybe webadmin as well?)

**Describe the bug**
webmap shows a blank page. both on pc and mobile. 

**To Reproduce**
start webadmin, webmap and rest of the scripts in [web], visit your webadmin page and click on map.

**Expected behavior**
it should show the map with players as blips on it

**Screenshots**
![Screenshot_20201031-044816_Brave](https://user-images.githubusercontent.com/24281147/97768526-ad057f00-1b34-11eb-9e41-997439d9705f.jpg)

**Version**

**Comment by turret001** [comment]
duplicate of #130 
sorry! i should've searched first..

**Comment by qaisjp** [comment]
Duplicate of #130

**Comment by qaisjp** [comment]
No problem
