### ISSUE TITLE
Delete [admin]/admin/conf/IpToCountryCompact.csv file from the repo

### ISSUE THREAD

**Issue by umithyo** [multitheftauto/mtasa-resources#242]
**I have added this repo as a submodule and every time I start/stop my server [admin]/admin/conf/IpToCountryCompact.csv gets modified. It is not supposed to be in the repo**

**Delete [admin]/admin/conf/IpToCountryCompact.csv as it is already generated**

**Comment by xLive** [comment]
Admin panel update that file if there is a new one this is why it's got modified

Can you explain why we should delete it?

**Comment by umithyo** [comment]
It is just infuriating seeing that file gets changed every time, also if admin panel updates the file why would you need to include it here? That doesn't make sense to me.

**Comment by xLive** [comment]
> It is just infuriating seeing that file gets changed every time
I don't think it's gets modified every time there is a check to prevent this from happening
https://github.com/multitheftauto/mtasa-resources/blob/2c6416a09697b9d8b812c182cff0955b09d753c5/%5Badmin%5D/admin/server/admin_ip2c.lua#L203

> if admin panel updates the file why would you need to include it here? That doesn't make sense to me

a backup must exist if the server can't access to MTA site for some reason

**Comment by umithyo** [comment]
Well I don't know if it's the best idea to keep that backup in here but whatever, I have found a solution for myself.

I added
```
[submodule "resources/[MTASA_RESOURCES]"]
	path = resources/[MTASA_RESOURCES]
	url = https://github.com/multitheftauto/mtasa-resources.git
        ignore = dirty <== this 
```
