### ISSUE TITLE
Map Editor Output Location

### ISSUE THREAD

**Issue by umithyo** [multitheftauto/mtasa-resources#244]
**Is your feature request related to a problem? Please describe.**
Yes, I cannot change the output directory of map files.

**Describe the solution you'd like**
Ability to change the location of newly added map files included in settings.xml or something.

**Comment by qaisjp** [comment]
by "output directory" do you mean the organizational directory? e.g. `[newmaps]`?

**Comment by umithyo** [comment]
> by "output directory" do you mean the organizational directory? e.g. `[newmaps]`?

Yeah, exactly.

**Comment by umithyo** [comment]
Can I add this feature and make a PR?

**Comment by qaisjp** [comment]
Sure

**Comment by jlillis** [comment]
Fixed in #245, but discussion continues in #287.
