### ISSUE TITLE
editor: Gamemodes list does not reset after creating a new map

### ISSUE THREAD

**Issue by xLive** [multitheftauto/mtasa-resources#269]
**Describe the bug**
Gamemodes list in the map settings does not reset after creating a new map

**To Reproduce**
1- start the editor and create/open a new map
2- open the map settings and add a gamemode to your map `race` for example and press `OK`
3- create a new map
4- open the map settings again and you will notice `race` is missing

**Expected behavior**
The gamemodes list should reset after creating a new map

**Screenshots**
Map 1
![image](https://user-images.githubusercontent.com/30420446/103581782-b5d84f80-4eed-11eb-8f49-04b1db291f93.png)
Map 2 (new map)
![image](https://user-images.githubusercontent.com/30420446/103581839-d3a5b480-4eed-11eb-9723-d9159e1ef223.png)

**Comment by jlillis** [comment]
I'm confused - it seems to be working as intended. The list of gamemodes added to a map is a property of the map itself, rather than the editor overall. Therefore, the list will be empty when creating a new map.

**Comment by xLive** [comment]
I found the problem
```lua
function passDefaultMapSettings()
	currentMapSettings = makeSettingsDefault()
	currentMapSettings.gamemodeSettings = {}
	currentMapSettings.addedGamemodes = {}
	doSaveNewMapSettings(currentMapSettings, true)
```	
no available gamemodes here
I'm gonna open a PR to fix it
