### ISSUE TITLE
webstats: deprecate flash player

### ISSUE THREAD

**Issue by jlillis** [multitheftauto/mtasa-resources#278]
**Which resource(s) have this problem?**
`webstats`

**Describe the bug**
The `webstats` resource uses flash player, which has been discontinued as of this year. This needs to be addressed by either:
- upgrading the resource
- deprecating it

**To Reproduce**
N/A

**Expected behavior**
N/A

**Screenshots**
N/A

**Version**
N/A

**Additional context**
https://www.adobe.com/products/flashplayer/end-of-life.html

**Comment by qaisjp** [comment]
**My opinion**

When you take out the flash parts of `webmap`, what is left behind?

Can the remainder `webmap` Lua code be considered salvageable, for a reimplementation of the frontend w/o flash?

- If so, deprecate (exclude from distributions via mtasa-blue installer configuration), and upgrade in the future.
- If not, delete the whole resource.

**Comment by patrikjuvonen** [comment]
I'm going to work on this!

**Comment by jlillis** [comment]
Had a little brain moment when filing this report - it's `webstats` that has this issue, not `webmap`. The `webmap` resource has it's own problem reported here: #130

**Comment by patrikjuvonen** [comment]
All web related resources could use some refreshing.

**Comment by jlillis** [comment]
> 
> 
> All web related resources could use some refreshing.

There is a discussion on that topic here: https://github.com/multitheftauto/mtasa-resources/discussions/279

**Comment by jhxp** [comment]
Test comment.

**Comment by jhxp** [comment]
Test comment.

**Comment by jhxp** [comment]
Test comment.
