### ISSUE TITLE
Fresh installation has errors

### ISSUE THREAD

**Issue by ciber96** [multitheftauto/mtasa-resources#280]
**Which resource(s) have this problem?**
admin

**Describe the bug**
Fresh installation of admin resources has sevral errors not present before and spams the console.

**To Reproduce**
1. Fresh install of Admin Resource

**Expected behavior**
No errors

**Screenshots**
https://i.ciber.dev/s/jWPBTgqBqgcnfpC/preview
https://i.ciber.dev/s/X7fFzbsWetDBtJ4/preview
https://i.ciber.dev/s/n6maxcGXDMNKbxb/preview

**Version**
Not aplicable

**Additional context**
Latest Version available from linux.mtasa.com

**Comment by sbx320** [comment]
Looks like there's an `end` too much here:

https://github.com/multitheftauto/mtasa-resources/commit/d237f279a5e6508864c296798a65c55b69139dd6#diff-cff77698f0b2306e72e28e9c7ded09859eaded7d1987c9c606a79fe7e9989dceR1268

We should have some sort of Github action to check if comitted files are valid Lua

**Comment by jlillis** [comment]
Fixed by #284
