### ISSUE TITLE
editor: allow organizational directory to be changed via save map UI

### ISSUE THREAD

**Issue by jlillis** [multitheftauto/mtasa-resources#287]
**Is your feature request related to a problem? Please describe.**
#245 added the ability to change the editor's organizational directory via settings in the admin panel. It would be cool to have the be editable via the save map UI so you can change the directory per-resource.

**Describe the solution you'd like**
The ability to switch the map organizational directory via the save menu.

**Describe alternatives you've considered**
N/A

**Additional context**
#244

**Comment by xLive** [comment]
just an idea for the save dialog:
![image](https://user-images.githubusercontent.com/30420446/110233373-9c2aa700-7f34-11eb-861a-7a1e8deded69.png)
what do you think?

**Comment by iDannz-Breno** [comment]
@xLive do you pretend to keep working on this?

**Comment by xLive** [comment]
> 
> 
> @xLive do you pretend to keep working on this?

No, feel free to work on it.

**Comment by iDannz-Breno** [comment]
Ok, thank you.
