### ISSUE TITLE
'killmessages' needs optimization

### ISSUE THREAD

**Issue by Dutchman101** [multitheftauto/mtasa-resources#331]
**Which resource(s) have this problem?**
[killmessages](https://github.com/multitheftauto/mtasa-resources/tree/master/%5Bgameplay%5D/killmessages)

**Describe the problem**
PR #69 (cc: @AboShanab) has worsened the optimization state of "killmessages" heavily.

Prior to the change, this resource would consume around 2% client CPU.. after the change, it can consume between 12% and 17%.

**To Reproduce**
Steps to reproduce the behaviour:
1. Run 'killmessages'
2. Get a decent amount of players on your server, actively killing eachother to fill the killfeed
3. Monitor client CPU usage (e.g /ipb - ingame performance browser), filter `killmessages` and put in option `-d`
4. Observe

Someone that's willing to, can evaluable possibilities to optimize that code. All of the surplus CPU usage is concentrated on [textlib.lua#L240](https://github.com/multitheftauto/mtasa-resources/blob/83884881f1a171ac5f77d76ed2da2f280fcd264b/%5Bgameplay%5D/killmessages/utils/textlib.lua#L240) which, during render, invokes [dxCreateCustomDX](https://github.com/multitheftauto/mtasa-resources/blob/83884881f1a171ac5f77d76ed2da2f280fcd264b/%5Bgameplay%5D/killmessages/utils/textlib.lua#L205) (looks like the real problem).

Sidenotes: 
1) I didn't really try to optimize it (or look for ways) myself, I also suck with DX calculations stuff.. just tracking this issue as it's supposed to be.
2) Note that if there's no feasible way to optimize it, the performance impact outweighs its benefits (fancy colors in killfeed).

**Expected behavior**
All default resources should be kept in a well-optimized state, and a PR that make it visually nicer shouldn't make it almost tenfold as unoptimized.

**Screenshots**
![cpu](https://user-images.githubusercontent.com/12105539/123354085-2ee26680-d563-11eb-987d-2ef3c8cd76e1.png)
Just an example - range is between 12% and 17%

**Version**
'killmessages' version 8bb20de

**Additional context**
We need to improve our code/PR review processes to also look at performance implications (in practise). I won't just say that, ill try take initiative on it in the future.

Also, if no one can find a satisfactory way to optimize killmessages soon, i plan on reverting PR #69 (while applying a tweak of removing player's HEX colorcodes in killfeed.. so it would be easy for players to make the transition & get used to it again. It will still look neater than before PR #69 got merged (before of which, it would be messy with player colorcodes in cleartext & cutting names in pieces on killfeed):
![image](https://user-images.githubusercontent.com/12105539/123354724-7f0df880-d564-11eb-8cd6-a7c73badc5ad.png) 

...and keep it reverted at least until someone wants to contribute the final optimization fix.

**Comment by iDannz1** [comment]
I think this resource deserves a rewrite, mainly because of this CPU usage and also because its code looks a little spaghetti. I can take a look in some hours...

**Comment by ricksterhd123** [comment]
> I think this resource deserves a rewrite, mainly because of this CPU usage and also because its code looks a little spaghetti. I can take a look in some hours...

If this is the case then we ought to implement vehicle kill detection for killers in hydra/hunter/rustler/rhino etc.

**Comment by Dutchman101** [comment]
> Also, if no one can find a satisfactory way to optimize killmessages soon, i plan on reverting PR #69 (while applying a tweak of removing player's HEX colorcodes in killfeed
> ![image](https://user-images.githubusercontent.com/12105539/123354724-7f0df880-d564-11eb-8cd6-a7c73badc5ad.png)

Reverting PR #69 is scheduled for Monday or soon after, due to the results of discussion:

![talk](https://user-images.githubusercontent.com/12105539/123521834-77ac3380-d6b9-11eb-854e-711ad5f10bb3.png)

At least for now to solve the immediate problem, until #332 refactor is finished.

**Comment by Dutchman101** [comment]
Initially fixed in 1275953 and then superseded by 2e356cb
