### ISSUE TITLE
custom handling doesn't work for aircraft

### ISSUE THREAD

**Issue by touhourailway** [multitheftauto/mtasa-resources#362]
the function setVehicleHandling doesn't work for air handling, and this just return false but not show at debug.

**Comment by itslewiswatson** [comment]
This doesn't pertain to a specific resource included here, rather MTA itself. It may be worth making an edit to mention this in [the wiki page for setVehicleHandling](https://wiki.multitheftauto.com/wiki/SetVehicleHandling) and/or opening an issue in [mtasa-blue](https://github.com/multitheftauto/mtasa-blue) asking for better support when a user alters an unsupported handling property on an aircraft.

**Comment by Dutchman101** [comment]
See [mtasa-blue issue #2426](https://github.com/multitheftauto/mtasa-blue/issues/2426), this was filed in the wrong repository. But @touhourailway, it also contains information on how you can make setVehicleHandling work on planes (not helicopters though)
