### ISSUE TITLE
password

### ISSUE THREAD

**Issue by rafalohaki** [multitheftauto/mtasa-resources#371]
what is login and password for web admin resourcebrowser?
how to add user to admin?

**Comment by TheNormalnij** [comment]
You don't need add any additional user. Just use your admin account login and password.
If you haven't any admin user, add a new user with using [this manual](https://wiki.multitheftauto.com/wiki/Server_Manual#Adding_administrators)

This is a bug tracker. Please, use [Wiki](https://wiki.multitheftauto.com/wiki/Main_Page) / [Discord](https://discord.gg/mtasa) / [Forum](https://forum.mtasa.com/) for support.

**Comment by rafalohaki** [comment]
thanks. 
ps. where can i set resources for auto start. speedmeter for example
