### ISSUE TITLE
Admin chat has no message string size limit

### ISSUE THREAD

**Issue by ricksterhd123** [multitheftauto/mtasa-resources#373]
**Which resource(s) have this problem?**

admin
**Describe the bug**

There's no limit to how much text can be put into each message. This can cause lag as a consequence to other admins, potentially crashing their MTA clients depending on how much text you put. Who knows, this could potentialy even crash the server if triggerServerEvent isn't non-blocking.

**To Reproduce**

Open admin panel, go to admin chat. This won't work on the /a command because the chatbox is limited as it should be!
Copy and paste as much text as possible into admin chat and submit the message.
Now each message sent after will cause freeze lag to other admins.

**Expected behavior**

You should not even be able to send that much text.

**Screenshots**

**Version**

Ver: 1.5.9-9.21035.0

**Additional context**

I found this out because I was the troll who did it

**Comment by iPollo** [comment]
Does this still need to be fixed?

**Comment by ricksterhd123** [comment]
Yes, feel free to fix it

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by francisco-create** [comment]
[](https://wiki.multitheftauto.com/wiki/GuiEditSetMaxLength) **This thread might be of use to you, my friend.**
