### ISSUE TITLE
editor: add some way to restore removed objects

### ISSUE THREAD

**Issue by iDannz1** [multitheftauto/mtasa-resources#374]
**Is your feature request related to a problem? Please describe.**
Apparently at this moment there is no way to restore objects that were removed from the original map... (we have to manually find and remove the correct line in the .map file)

**Describe the solution you'd like**
As we can list the changes through this window, maybe we could add some button to restore the removed object?
![image](https://user-images.githubusercontent.com/38073795/147357644-afe0db67-795f-4b6c-ac85-198c25a7e90e.png)
![image](https://user-images.githubusercontent.com/38073795/147357506-07f988a1-46bc-48c8-8e6b-2798d2d1f61e.png)
(we can also add navigation using the keyboard arrows to the above list, as is already possible in other lists, such as the list of objects/ids)

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Vampiiree** [comment]
Actually, there's a way of restoring world objects using the 'current elements' tool:
- Click twice in the line so it opens the properties
- There will be a symbol (>) on the lower right side
- Press 'delete'

https://i.imgur.com/ZNsnE24.png

**Comment by psyhiic** [comment]
> Actually, there's a way of restoring world objects using the 'current elements' tool:
> 
> * Click twice in the line so it opens the properties
> * There will be a symbol (>) on the lower right side
> * Press 'delete'
> 
> https://i.imgur.com/ZNsnE24.png

But perhaps he gave a more practical idea of ​​restoring the removed object.

**Comment by Vampiiree** [comment]
Well, I didn't say that his idea isn't good. I just pointed out that it already exists within the tool he mentioned.

**Comment by Fernando-A-Rocha** [comment]
+1

Button to restore removed world object from the list + delete key to restore + navigating with arrow keys

All good enhancements

**Comment by iDannz1** [comment]
> Actually, there's a way of restoring world objects using the 'current elements' tool:
> 
> * Click twice in the line so it opens the properties
> * There will be a symbol (>) on the lower right side
> * Press 'delete'
> 
> https://i.imgur.com/ZNsnE24.png

Yeah, I didn't know about that...

**Comment by psyhiic** [comment]
> > Actually, there's a way of restoring world objects using the 'current elements' tool:
> > 
> > * Click twice in the line so it opens the properties
> > * There will be a symbol (>) on the lower right side
> > * Press 'delete'
> > 
> > https://i.imgur.com/ZNsnE24.png
> 
> Yeah, I didn't know about that...

But the Issue you created talking about restoring the object is great, I had in mind to create a function to restore the removed objects more practical.

**Comment by iDannz1** [comment]
Another thing that I believe can be fixed if someone decides to touch this part of the code: https://streamable.com/49fe3i

*If you select an element from the "Current Elements" list and then press the "delete" key on your keyboard, it will visually disappear, but it will remain bugged in the list. (if you re-select and press "delete" again, it will delete the next element, and the next list item will be bugged aswell)

**Comment by Haxardous** [comment]
fixed by #401
