### ISSUE TITLE
elementbrowser is broken

### ISSUE THREAD

**Issue by iDannz1** [multitheftauto/mtasa-resources#379]
**Which resource(s) have this problem?**

elementbrowser

**To Reproduce**

1 - start the `elementbrowser` resource
2 - open http://server_ip:http_port
3 - select the "Element browser" menu option

**Expected behavior**

it should work 😄

**Screenshots**

![image](https://user-images.githubusercontent.com/38073795/153538913-55cda9d4-2450-48e4-a12e-168d82203431.png)
![image](https://user-images.githubusercontent.com/38073795/153539196-8cf39c45-69aa-41db-b359-e13dd2ffb067.png)

**Version**

MTA:SA Server 1.5.9-release-21048

**Additional context**

I haven't checked the code, but I belive its the same thing @ArranTuna fixed in [this commit](https://github.com/multitheftauto/mtasa-resources/commit/37348cecb60a6c999c316398a17f866d54569953)

**Comment by ArranTuna** [comment]
After looking at the javascript, I have no idea how to fix it, the script is barely understandable to me.

**Comment by 4O4** [comment]
It was broken by the changes to `json.js` during webmap upgrade: [[web]/ajax/json.js](https://github.com/multitheftauto/mtasa-resources/commit/8e2b12b6d012c89a063a8c5e9873454f8d3ab7e3#diff-adfe7968957f2a79a6ec34240a7f5d87186a3b1a64b8c52baa91f1f78c5c7a29)

**Comment by 4O4** [comment]
@patrikjuvonen are you planning to work on that or already started? I've prepared a fix that removes the `json.js` altogether because it's some ancient history that is no longer needed and I wouldn't trust it as much as I trust the native `JSON.parse` and `stringify`. I could send a PR later this evening.

**Comment by patrikjuvonen** [comment]
> @patrikjuvonen are you planning to work on that or already started? I've prepared a fix that removes the `json.js` altogether because it's some ancient history that is no longer needed and I wouldn't trust it as much as I trust the native `JSON.parse` and `stringify`. I could send a PR later this evening.

@4O4 Go ahead please! Thanks.
