### ISSUE TITLE
Auto braking with default freeroam gamemode

### ISSUE THREAD

**Issue by Xenius97** [multitheftauto/mtasa-resources#419]
**Which resource(s) have this problem?**
freeroam

**Describe the bug**
If you release acceleration btn your car will braking automatically with default freeroam gamemode

**To Reproduce**
Get a car

**Screenshots**
https://streamable.com/xs935s

**Version**
Latest

**Comment by Dark-Dragon** [comment]
I believe what you're experiencing is a side-effekt of high-fps in gta, not any particular resource. You can check if the problem persists after using setFPSLimit(45) or entering fps_limit=45 in the F8 console.

**Comment by Xenius97** [comment]
Ye it was fps issue too, i've transfering this to mtasa-blue issues
