### ISSUE TITLE
Resource to create, modify material

### ISSUE THREAD

**Issue by CrosRoad95** [multitheftauto/mtasa-resources#421]
Everyone who tried to make something related to shaders in mta know they are hard.
An idea i'm proposing is to add a resource that goal is to make different materials ( backed by shaders ) simillar to what most game engines do.
So for example

```lua
local material = exports.materials:createBlankMaterial()
exports.materials:setMaterialDiffuse(material, tocolor(255,0,0,255))
exports.materials:setMaterialTexture(material, 0, "mreow.png")
engineApplyShaderToWorldTexture(material, object)
```
this is simple example, but it might support simillar functionality to game engines such a blending, animations, multiple textures ect.

**Comment by jlillis** [comment]
Closing this feature proposal for now. If anyone wants to reopen it with a PR go ahead.
