### ISSUE TITLE
editor_main: OOP node in editor_test

### ISSUE THREAD

**Issue by dnl-k** [multitheftauto/mtasa-resources#424]
So I recently reinstalled MTA, fired up the editor and loaded one of my maps only to find it not working.
Took me a while to find out that the editor test mode no longer enables OOP.. as seen in 95f3c36307512bb35e7efb727e101c1bbc136564
While it may be true that not many people use OOP, it's still a feature that should work right out of the box.

**Comment by jlillis** [comment]
[I was afraid this was a possibility. ](https://github.com/multitheftauto/mtasa-resources/pull/389#pullrequestreview-1005091142) Just to make sure I'm understanding fully, do you have additional map scripts in your maps that rely on OOP being enabled or did something else break? If you have custom map scripts that use OOP, how common are they/how many maps do you have that are using them?

**Comment by dnl-k** [comment]
I have been and would like to continue using additional scripts that are written with OOP.
I don't know how common they are in general, probably not that much. But that shouldn't really matter?

**Comment by jlillis** [comment]
After some discussions on the dev discord the concern is that [just enabling OOP in a resource's meta.xml will cause an increase in memory usage and performance penalty of about 20%](https://github.com/multitheftauto/mtasa-resources/pull/364#issuecomment-957294739). This would mean that by having the editor generate map resources with OOP enabled we would automatically be enabling a memory/cpu penalty for all map resources - all of which include the `mapEditorScriptingExtension` scripts at minimum. This is (and was) problematic.

I realize that this change in default behavior is frustrating to deal with but given these facts I think the best course of action is to advise users to either (a) don't use OOP in map resource scripts or (b) have them enable OOP manually.

**Comment by jlillis** [comment]
Going to close this for now as there haven't been any additional complaints about this. I advise working around this by enabling OOP yourself on an as-needed basis.
