### ISSUE TITLE
editor_main: Elements with collisions disabled not selectable

### ISSUE THREAD

**Issue by dnl-k** [multitheftauto/mtasa-resources#427]
Elements with collisions disabled through the properties menu are **no longer** selectable without High Sensitivity Mode (e) enabled.
Intentional or not, it's annoying to work with.

Edit: Reloading the map makes the element selectable without High Sens Mode.

**Comment by jlillis** [comment]
Confirmed. I'm not sure if it's intentional or not, but if it's a recent change in behavior I'd consider it a bug. Would like some more feedback first since I don't use or work on the editor very often.

**Comment by dnl-k** [comment]
Caused by https://github.com/multitheftauto/mtasa-resources/commit/aeed6838b79756002f6ac46af1baf4a5476d9493#diff-385f1758e22086658aaf755e940abf9040bee3bdb486fd6e3dab4dcc0d0762a0R157

Objects with no collisions are not picked up by processLineOfSight
Since adding the property setter, objects collisions actually get disabled in the editor - unlike before
