### ISSUE TITLE
editor_main: Rotations are broken

### ISSUE THREAD

**Issue by dnl-k** [multitheftauto/mtasa-resources#428]
I'm assuming that ced470eb0ead7c48df948a17533fda8cbe656b0d the culprit is.
Some situations that I've came across:

Rotating an object around it's Z axis to a value not being 0, 90, 180 or 270 and then attempting to rotate either the X or Y axis results in both (X and Y) axes rotating instead of just one. That definitely wasn't the case before.

Some objects (I've tested it with ID 18362) when placed and rotated on all axes get messed up upon entering test mode or saving and reloading.
Rotation before save:
324.16809082031, 20.187377929688, 228.21350097656

Rotation after save and reload:
322.4267578125, 16.243286132812, 216.06262207031

**Comment by jlillis** [comment]
I can't reproduce this on my end even when using the model ID you tested with. Are you using the new collision/rotation patches available in the editor settings?

**Comment by dnl-k** [comment]
I've tried it with both on and off, same result.
Everything else is also default as it's a fresh install

**Comment by Zangomangu** [comment]
please try again with the changes in #430 
attached here [editor_main.zip](https://github.com/multitheftauto/mtasa-resources/files/11313513/editor_main.zip)

it should save and reload properly

**Comment by dnl-k** [comment]
> please try again with the changes in #430 attached here [editor_main.zip](https://github.com/multitheftauto/mtasa-resources/files/11313513/editor_main.zip)
> 
> it should save and reload properly

It does indeed work properly.
Any idea about the other issue?

**Comment by Zangomangu** [comment]
Well it's not an issue, it's how it's supposed to work

- rotate around world axis (default: lctrl)
- rotate around object axis (default: rctrl)

The old implementation wasn't correct (even if we're used to it)
You can still modify the angles directly in the properties

**Comment by dnl-k** [comment]
Oh well I certainly didn't know that.
However, I do think that it should be switched around by default as everyone is used to the old implementation which basically rotated around the objects axis but on lctrl.

**Comment by Zangomangu** [comment]
The old implementation didn't rotate around object axes. I'm talking about the right/forwards/up axes here (local space) drawn with red/green/blue in editor. 
take a look at the video in #400 to see the difference. 

But yeah rctrl rotation is more intuitive to use and the two can be switched - but the current lctrl is closer to the old behavior
