### ISSUE TITLE
Map Editor bug

### ISSUE THREAD

**Issue by JacobItaly** [multitheftauto/mtasa-resources#441]
### Describe the bug

Hello!

I have this bug since 1.5 for some time now - basically when I turn on Slow Mode (for objects, to slowly put them in the map) and then want to switch to "faster mode" or "default mode" it doesn't work. It always happens when I bind slow mode to a random key (ex: i have slowmode on [,] and fast mode on [.] and when turning on slow mode, clicking [.] doesn't do nothing) or maybe i'm just missing a point here or something.

### Steps to reproduce

1, Go to Settings
2. Go to Key Bindings
3. Change "Slow Speed modifier" to any key, as well as "Fast Speed Modifier" (in this case - , and .)
4. Enter map editor
5. Select desired object, press [,] you'll notice that it will work and Slow Speed modifier will be applied correctly
6. When you press [.] now, nothing will happen

### Version

Client: 1.5.9 Windows / now 1.6 Windows

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

**Comment by Dark-Dragon** [comment]
I can't reproduce the issue. So from what I can tell the issue only occurs when you use a non-default keybinding, right? So does that mean it will function properly when you have it on the default lshift and lalt? Did this work on previous versions? Also are you pressing the keys once or are you holding them? They're meant to only apply to the object movement speed while you hold them down.

**Comment by jlillis** [comment]
Since this issue hasn't been reproduced in over a year I'm going to close issue for now.
