### ISSUE TITLE
race / general: certain objects causing rendering issues

### ISSUE THREAD

**Issue by brianmta** [multitheftauto/mtasa-resources#450]
certain objects have been causing rendering issues on Race Deathmatch maps for multiple years now. when these objects are present in a map, many objects around them start flashing and disappearing. the issue is still present in the latest nightly of 1.6.

few of these objects are: 8620 (shown on video), 16176

Video showing the bug (mute before playing, sorry about the background noise): 
https://www.youtube.com/watch?v=Hz6rPXyrX_8&ab_channel=B%C3%A1lintHorv%C3%A1th

**Comment by jlillis** [comment]
I believe this is an issue that needs to be addressed in `mtasa-blue`, not the resources.
