### ISSUE TITLE
Chat messages sent twice

### ISSUE THREAD

**Issue by Nico8340** [multitheftauto/mtasa-resources#460]
**Which resource(s) have this problem?**
Playercolors

**Describe the bug**
Playercolors also has an event handler that listens to onPlayerChat, so every chat message is sent twice.

**To Reproduce**
Steps to reproduce the behaviour:
1. Start playercolors and freeroam (Since 1.6, both start by default)
2. Send a message in the chat
3. See the message appear twice

**Expected behavior**
The message is sent only once.

**Screenshots**
![image](https://github.com/multitheftauto/mtasa-resources/assets/122193236/6beb7f1b-ffa5-4a41-abb9-8e8c1a5328ea)

**Version**
Client ver: Multi Theft Auto v1.6-release-22364
Client OS: Windows 11

Server ver:  MTA:SA Server v1.6-release-22361 (Latest nightly)
Server OS: Windows 11

**Additional context**
-

**Comment by Nico8340** [comment]
https://github.com/multitheftauto/mtasa-resources/pull/461

**Comment by Nico8340** [comment]
#463

**Comment by Fernando-A-Rocha** [comment]
High priority bug to be fixed on #463
