### ISSUE TITLE
playerblips: When a player joins a team, his blip color does not update

### ISSUE THREAD

**Issue by T-MaxWiese-T** [multitheftauto/mtasa-resources#486]
**Which resource(s) have this problem?**
playerblips

**Describe the bug**
If `use_team_colors` or `use_nametag_colors` is set to `true` and the player joins a team, his blip color does not update.
However, it will be updated when a player leaves, enters, dies or is killed on the server. This means it is not a serious bug.

**To Reproduce**
1. `use_team_colors` or `use_nametag_colors` must be set to `true`.
2. Join a team. 

**Expected behavior**
When the player joins a team, his blip color should update.

**Screenshots**
None

**Version**
server 1.6

**Additional context**
There are currently no events for when a player joins a team. But there is already a pull request for this event https://github.com/multitheftauto/mtasa-blue/pull/3370

**Comment by Dutchman101** [comment]
> There are currently no events for when a player joins a team. But there is already a pull request for this event [multitheftauto/mtasa-blue#3370](https://github.com/multitheftauto/mtasa-blue/pull/3370)

It's been merged (onPlayerTeamChange), maybe you want to implement it to fix this issue? Think about minimum server version requirement as well
@T-MaxWiese-T

**Comment by T-MaxWiese-T** [comment]
> > There are currently no events for when a player joins a team. But there is already a pull request for this event [multitheftauto/mtasa-blue#3370](https://github.com/multitheftauto/mtasa-blue/pull/3370)
> 
> It's been merged (onPlayerTeamChange), maybe you want to implement it to fix this issue? Think about minimum server version requirement as well @T-MaxWiese-T

I can implement it if the event is part of a stable Linux server package which can be found here: https://linux.multitheftauto.com . 
It makes no sense to add the event if it is not part of the stable Linux server package, as most server owners and hosting providers probably use this version.
