### ISSUE TITLE
Rotating an object bug

### ISSUE THREAD

**Issue by NeblaStuff** [multitheftauto/mtasa-resources#496]
**Which resource(s) have this problem?**
Map editor

**Describe the bug**
In map editor; you are not able to rotate any world objects sometimes.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Map editor in Multi Theft Auto
2. select any object you want to rotate & set object Y rotation to 90 or 270 and then press ok.
3. Select the object again & Hold press Lctrl + arrow left or right
4. It simply not rotating the object, stuck & glitching

**Expected behavior**
You should be able to rotate the object in Z rotation when you rotate the object in X,Y rotations without having any bugs.
![mta-screen_2024-06-09_18-59-33](https://github.com/multitheftauto/mtasa-resources/assets/79787878/8317cc01-eb38-488c-b404-197ef46b462c)

**Version**
MTA.1.6.0

**Additional context**
many mappers having this issue so some of them trying to hire old mta version servers for mapping because there had no bugs in previous mta versions

**Comment by Dark-Dragon** [comment]
Yes, I can reproduce this issue as described.

**Comment by Dutchman101** [comment]
> Yes, I can reproduce this issue as described.
@Dark-Dragon 
Do you want to fix it?

**Comment by Fernando-A-Rocha** [comment]
I can reproduce this. Demo video: https://streamable.com/j6xsxp

This object will not rotate when RY is 90. I assume there are some math calculations being done wrong. I will check the code.

**Comment by Fernando-A-Rocha** [comment]
Presumably the problem is here https://github.com/multitheftauto/mtasa-resources/blob/master/%5Beditor%5D/editor_main/client/rotation.lua#L41
