### ISSUE TITLE
internetradio: GUI window of the resource "helpmanager" collides with the "internetradio" GUI window

### ISSUE THREAD

**Issue by T-MaxWiese-T** [multitheftauto/mtasa-resources#497]
**Which resource(s) have this problem?**
internetradio

**Describe the bug**
If you press F9, both the GUI window of the resource "helpmanager" and the GUI window of the resource "internetradio" will open.

**To Reproduce**
1. "helpmanager" resource and "internetradio" resource must be running. 
2. Press the F9 key.

**Expected behavior**
It should be possible to open the GUI window of the "internetradio" resource with another button.

**Screenshots**
None

**Version**
- server/client version 1.6

**Additional context**
None

**Comment by Fernando-A-Rocha** [comment]
There appear to be commands to open the GUI
https://github.com/multitheftauto/mtasa-resources/blob/master/%5Bgameplay%5D/internetradio/server.lua#L71

The F9 bind can be removed? Idk if it's a good idea to change it to another key. Some server might already be using it for something else.

**Comment by T-MaxWiese-T** [comment]
> The F9 bind can be removed? Idk if it's a good idea to change it to another key. Some server might already be using it for something else.

So it doesn't conflict with the standard configuration. I would leave it at this key but there should be a setting with which you can change the key.

**Comment by JanitoElPadrino** [comment]
There is an injector that Cheaters uses, it is still working called Sharingan
