### ISSUE TITLE
Freeroam freezetime causes slightly noticible screen flickering every 5 seconds

### ISSUE THREAD

**Issue by ricksterhd123** [multitheftauto/mtasa-resources#529]
**Which resource(s) have this problem?**

freeroam

**Describe the bug**

When the 'freeze' time checkbox is set every 5 seconds the screen flickers to sync the time and weather. It's bad for recording and other purposes.

**To Reproduce**

1. press f1
2. on the bottom of the panel, click 'freeze'
3. experience slight screen flickering

**Expected behavior**

There shouldn't be any screen flickering

**Version**

1.6.0

**Comment by Proxy-99** [comment]
related to https://github.com/multitheftauto/mtasa-blue/pull/3567
