### ISSUE TITLE
Maps Script Loader

### ISSUE THREAD

**Issue by Proxy-99** [multitheftauto/mtasa-resources#550]
Adding a  new resource Map Script loader will be useful for multi game modes scripting and loading client scritps from a map without rely on loading a resource and start it

**Comment by Fernando-A-Rocha** [comment]
I don't think I understand. Example?

**Comment by MegadreamsBE** [comment]
> I don't think I understand. Example?

Multi-gamemodes receive map files and scripts from the server, they then load it in with loadstring. They keep track of elements and other changes to revert once the map unloads. As it's not related to any gamemode, I feel it's out of scope for the default resources. Not to mention that it's very easy for it to go out of date and become insecure.

**Comment by Fernando-A-Rocha** [comment]
Nice, it makes map scripts more tied to the maps themselves.

**Comment by Proxy-99** [comment]
> > I don't think I understand. Example?
> 
> Multi-gamemodes receive map files and scripts from the server, they then load it in with loadstring. They keep track of elements and other changes to revert once the map unloads. As it's not related to any gamemode, I feel it's out of scope for the default resources. Not to mention that it's very easy for it to go out of date and become insecure.

We can add basic functionality and simple loader to help developers understand how to get started making their own code I think this is going be a very useful resource to have

**Comment by jlillis** [comment]
This seems out-of-scope given the way the default gamemodes are structured. If you want to open a PR for this in the future go ahead, but I don't think this is a realistic feature request.
